settings:
  title: 'Status Page'
  url: 'https://wzjk.ga' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Cloudreve-Heroku # unique identifier
    name: cloudreve-heroku.herokuapp.com
    description: 'Cloudreve-Heroku' # default=empty
    url: 'https://cloudreve-heroku.herokuapp.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: MS365 E5 Renew X Fly.io
    name: E5.fly.dev
    description: 'MS365 E5 Renew X Fly.io'
    url: 'https://e5.fly.dev'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: Azure Domain Check
    name: azcheck.herokuapp.com
    description: 'Azure Domain Check'
    url: 'https://azcheck.herokuapp.com'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
