settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Cloudreve-Heroku # unique identifier
    name: Cloudreve-Heroku
    description: 'cloudreve-heroku.herokuapp.com' # default=empty
    url: 'https://cloudreve-heroku.herokuapp.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: MS365 E5 Renew X Fly.io
    name: MS365 E5 Renew X Fly.io
    description: 'e5.fly.dev'
    url: 'https://e5.fly.dev/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

